### ISSUE TITLE
Exclude chromosomes/regions from analysis

### ISSUE THREAD

**Issue by gbdias** [malonge/RaGOO#2]
Hi,

- The RaGOO preprint mentions the ability to provide a set of genomic regions as gff3 so that the analysis will not break chimeric contigs at those segments. 
> RaGOO can optionally avoid breaking chimeric intervals at loci within genomic coordinates specified by a gff3 file, such as to avoid disrupting gene models identified in the de novo assembly.
- When looking at the ragoo.py options, I can only fin the -e option, which seems to ignore complete chromosomes/scaffods from the analysis.
- Is the gff3 option implemented in the current version of RaGOO?
- Also, could you provide a little more detail on how the exclude option `-e` works? Specifically, are the provided sequences completely removed from the analysis?

Btw, this tool is very useful and seems to work very well! Congratulations! 🎉

**Comment by malonge** [comment]
Hi There,

Thanks for being the first to open up an issue! Glad you like the tool.

For the first point, there has always been a -gff option, though it was hidden. I have since added it as an explicit command line flag. Though you could use it as a hidden flag in your download, I would recommend updating to the latest version anyways. Hopefully, the wiki pages for [breaking chimeric contigs](https://github.com/malonge/RaGOO/wiki/Breaking-Chimeric-Contigs) and [gff lift-over](https://github.com/malonge/RaGOO/wiki/GFF-File-Lift-Over) will also be helpful.

As for the second question, the `-e` flag will not build pseudomolecules corresponding to any reference header provided. For example, say the reference genome has a mitochondrial genome. If one doesn't want to build a pseudomolecule corresponding to that mitochondrial genome, one could use the `-e` flag to exclude it.

I should mention that the minimap2 alignments include all reference sequences regardless. But alignments to chromosomes specified in `-e` are just ignored.

**Comment by gbdias** [comment]
- Thanks for the quick reply!
- I'll admit I haven't noticed the wiki pages, and they do contain the answer to my question about the gff flag.

Thanks for all the info.

**Comment by malonge** [comment]
They are brand new so I hope you find them helpful!
