### ISSUE TITLE
Error in  liftover script 

### ISSUE THREAD

**Issue by ewafula** [malonge/RaGOO#20]
Hi Michael, 

I keep getting the following error message when trying to lift genes from several reference genome following RaGOO scaffolding. Any idea of how to solve this? 

```
python /scratch/biotools/software/assembly/RaGOO-1.1/lift_over.py -g 100 ragoo_output/chimera_break/PC_chr.intra.chimera_broken.gff orderings.fofn ragoo_output/chimera_break/PC_CM_merged_pilon.intra.chimera.broken.fa.fai > genes.ragoo.gff
Traceback (most recent call last):
  File "/scratch/biotools/software/assembly/RaGOO-1.1/lift_over.py", line 84, in <module>
    new_header = ctg_chr[gff_header]
KeyError: 'Chr1'
```

**Comment by malonge** [comment]
Hi there,

Would you be willing to email me the files so I can debug? You can send them to malonge11@gmail.com

Thanks

**Comment by ewafula** [comment]
Sure, Michael. I will am sending the files.

**Comment by malonge** [comment]
Thanks for sending the files. The problem is actually a misunderstanding of the functionality of the lift-over tool. The tool is intended for lifting over gene models with respect to contigs to the pseudomolecules created from those contigs. So in your case, you would hypothetically lift over gene models associated with `PC_CM_merged_pilon.fasta`. That way, you would have those same gene models but with respect to the final `ragoo.fasta` file.

Unless I am mistaken, you would like to lift-over gene models from your reference genome to your new ordered and oriented genome. For this, you would need to use something like UCSC liftover or [paftools](https://github.com/lh3/minimap2/tree/master/misc).

I apologize for the confusion. I will check the documentation and make this more clear.

**Comment by ewafula** [comment]
Okay, Michael. That makes sense now. I’ll try the tools you’ve mentioned
 to  Liftover annotations from the reference genomes to my RaGOO
pseudomolecules

Thank you!
