### ISSUE TITLE
anchored position and orient file between the original scaffolds and the final assembly

### ISSUE THREAD

**Issue by rapaJiahe** [malonge/RaGOO#3]
Hi,

thank you for your softare, ragoo works well in my genome. and i have two questions when i use this software.  

I want to know, is there any quick way for me to generate the anchored position and orient file between the original scaffolds and the final assembly (i. e. agp file or gfa file)?

there are many misjoins in my orginal scaffolds, and I want to use Hi-C scaffolding results (agp result) to correct and improve the ragoo assembly results.  is there any softwares or sugesstions for me to do this work?

thank you very much.

Best,

He

**Comment by malonge** [comment]
Hi He,

Thank you. Glad it is working well. 

I don't have anything to make an agp or gfa file (though I have considered it). However, I do have a script that makes a bed file for each contig relative to the final pseudochromsome coordinates. The script is `ragoo_utilities/get_contig_borders.py`. It's a little rough, which is why I haven't mentioned it in the documentation, but hopefully, it is straight-forward to use. If not, let me know and I can help you out.

As for orientation, those can be found in the files in `ragoo_output/orderings`.

As for misjoins, firstly you can try to use the `-b` mode which will break large chimeric contigs. In our preprint, we also use [Juicebox Assembly Tools](https://github.com/aidenlab/Juicebox/wiki/Juicebox-Assembly-Tools) to manually correct some small errors with Hi-C data.

**Comment by rapaJiahe** [comment]
thank  you so much for your quick reply!

it works. if possible, i think you can add Hi-C support in your update version, i think it will be better to group and anchor repeat sequences and get a more reliable results.
 
Best,
He

**Comment by malonge** [comment]
It is certainly a consideration. I don't know of any Hi-C post-scaffolding tools that are out there (besides JBAT). The original scope of RaGOO is just to do assembly-reference comparison without the integration of raw reads or other data-types, though I agree that are many potential applications.
