### ISSUE TITLE
Difference between RaGOO and RagTag

### ISSUE THREAD

**Issue by XMTian** [malonge/RaGOO#73]
Hello,

Could you tell me what's the difference between RaGOO and RaGOO's successor, RagTag?

**Comment by malonge** [comment]
Hi there,

For now, the fundamental functionality is the same. I hope to have a formal description of the differences somewhere soon. In the meantime, here are some differences.

1. The scaffolding and correction accuracy has improved. 

2. Many features are much faster (sequence IO) or use much less memory (e.g. contig correction with validation)

3. There are some new features. One can use Nucmer instead of Minimap2, and one can pass custom parameters to the aligner. Alignments can also be filtered in more ways. One can also infer gap sizes from the reference genome alignments. There some others as well.

4. The software design has improved. The intermediate output is especially cleaner. There is also a new testing suite (though I am working on making the test data public). 

5. RagTag is available on conda and PyPI 

Aside from those differences, there are two primary reasons why one should switch to RagTag:

1. RaGOO will eventually be deprecated

2. We will be adding new features to RagTag

The new RagTag feature I am working on currently is the ability to use multiple reference genomes for scaffolding. And once it is ready, you can use the AGP files generated today to use the feature. So I definitely recommend using RagTag and saving output in case it can be used for future features.

Thanks,

**Comment by XMTian** [comment]
Thank you so much for your detailed explanation. 
It's super clear after your explanation.
