### ISSUE TITLE
Bionano scaffolding after or before RaGOO？

### ISSUE THREAD

**Issue by baozg** [malonge/RaGOO#9]
Hi，

I have contig fasta which assemblyed by the Falcon-Unzip, Should I do the Bionano hybrid scaffolding before the RaGoo scaffolding or after？

**Comment by malonge** [comment]
If your reference is chromosome-scale, I would do RaGOO last. That's because, in theory, if RaGOO establishes a chromosome-scale assembly based on the reference, then no more scaffolding is needed. There is also virtue to doing as many "*de novo*" steps as possible before the reference-guided step.

That said, after the bionano scaffolding, I recomend trying RaGOO with and without chimeric contig correction (-b), just incase the bionano scaffolding made any false joins.
